# Generated by Django 4.1.7 on 2023-04-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('info', models.TextField(blank=True, db_index=True)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
