# Generated by Django 4.1.7 on 2023-04-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cats',
            field=models.ManyToManyField(blank=True, related_name='products', to='stor.category'),
        ),
    ]
