# Generated by Django 4.1.7 on 2023-05-14 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0004_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-price']},
        ),
    ]
