# Generated by Django 4.1.7 on 2023-05-20 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0006_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Product',
            new_name='product',
        ),
    ]
